name: Notify Discord on Commit

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"📌 Commit mới trên \`${{ github.ref_name }}\`: ${{ github.event.head_commit.message }} bởi ${{ github.actor }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
